os: linux
dist: bionic
language: python
python:
  - "3.9"
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
    - python3-gi                              # GObject
    - libgirepository1.0-dev                  # GObject
    - gir1.2-gtk-3.0                          # gi.repository.gtk
    - gettext                                 # msgfmt
install:
  - pip install -r requirements_travis.txt
script:
  - python -m compileall gptrace.py setup.py gptrace
  - python -m pycodestyle gptrace.py setup.py gptrace
  - python -m flake8 gptrace.py setup.py gptrace
  - python -m build --outdir=dist .
  - python -m pip install --verbose dist/*.whl
  - python -m pip list
  - python -m pip freeze
  - ls -laR .
  - python -m pip uninstall --yes --verbose gptrace
