language: python
python:
  - "3.9"
install:
  - pip install -r requirements_travis.txt
script:
  - python -m compileall .
  - python -m pycodestyle .
  - python -m flake8 .
  - python setup.py install --optimize=1 --root=build
  - ls -laR build
